### ISSUE TITLE
Google Colab - CUDA Function Error: invalid device function

### ISSUE THREAD

**Issue by dolejs-jan** [voxcraft/voxcraft-sim#16]
When running voxcraft-sim in Google Colab one gets a _**CUDA Function Error: invalid device function**_.
This is caused by the difference in GPU compute capability (Tesla K80 used by Google has cc [3.7](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)).

This can be fixed by adding _**-gencode=arch=compute_37,code=sm_37**_ to cuda flags in _**CMakeLists.txt**_.

**Comment by liusida** [comment]
Thanks, @egoranger

I've added an auto-detection. Waiting for others to review.
