### ISSUE TITLE
[enchancement] Try to design a even simpler but more powerful configuration file format for experiment

### ISSUE THREAD

**Issue by liusida** [voxcraft/voxcraft-sim#2]
Currently we are using VXA/VXD files as configuration files. The main problem is that this legacy format cannot support arbitrary initial position/orientation/velocity etc., everything needs to start from a lattice.

We should design a new file format so that we can define what initial condition we need for our experiment.

The VXA/VXD format should be preserved since we have experiments already written in that format.

**Comment by skriegman** [comment]
Low priority, but if we redesign the file format, one thing that we might want to think about is creating a symbol/expression that indicates there is no material in this layer for N consecutive voxel slots. This would save a good amount of IO time when simulating high resolution bodies and/or sparsely filled worlds (e.g. petri dishes).
