### ISSUE TITLE
Changing Phase/Amplitude/Freq of temp on a per-material basis

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#22]
Right now it looks like properties such as TempPeriod and TempAmplitude are fixed at the environmental level.  But is there a way to change them on a per-material basis?  For instance maybe I want to control two material types, one that has an amplitude of 15 degrees and a period of 0.2s, and a second material with an amplitude of 5 and a period of 0.1s.

(Obviously this makes more sense if we think about pneumatically actuating sets of connected voxels in a silicone robot, rather than varying the temperature)

**Comment by skriegman** [comment]
@jrieffel do you want to try to implement this and submit a pull request? We have our hands full/overflowing at the moment.

**Comment by jrieffel** [comment]
someday! thanks!

**Comment by jrieffel** [comment]
I think I've found part of what I need in the VXA.VXC.Structure.PhaseOffset property, although I'm
