### ISSUE TITLE
Understanding parameter values of viz vs sim

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#24]
I'm able to get interesting and stable simulations from voxcraft-viz's sandbox, using a timestep of 1 and a "Vary Temperature" of 1.  These simulations appear to run in realtime.

When I run what I think i is the same setup, with a `TempPeriod` of 1 and a `StopConditionFormula` of 10 and a `DtFrac` of 1, a single simulation takes a VERY long time (20+ minutes).  

Could you help me understand the relation between the simulator properties and the sandbox properties?

**Comment by skriegman** [comment]
https://github.com/voxcraft/voxcraft-sim/blob/master/readme_before_reporting_issues.md

**Comment by skriegman** [comment]
Thanks for pointing this out. We will make sure this is clear in the docs we are presently updating
https://voxcraft.readthedocs.io/en/latest/
