### ISSUE TITLE
GPU error when running node worker

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#26]
I get the following printed to a history file when running vx3_node_worker.  I have an NVIDIA Quadro K1200 (rev a2), and I'm using the custom CMake file for my GPU you provided in a separate thread.

1 GPU found.
=== set device to 0 for 1 simulations ===

Total GPU memory 4236902400 bytes.
Set GPU heap size to be 2118451200 bytes.

/home/rieffelj/src/voxcraft-sim/src/VX3/VX3_SimulationManager.cu(415): CUDA Func
tion Error: too many resources requested for launch 
Running simulation locally by default.
./vx3_node_worker -i workspace/locally/20200731155914.vxt -o workspace/locally/2
0200731155914.vxr

**Comment by liusida** [comment]
it says CUDA Func
tion Error: too many resources requested for launch.
i guess it's the reason.

**Comment by jrieffel** [comment]
That is a tautological diagnosis. Where in your code is it requesting too many resources?

Restarting sometimes resolves the issue, briefly.

**Comment by skriegman** [comment]
@jrieffel 
https://github.com/voxcraft/voxcraft-sim/blob/master/readme_before_reporting_issues.md

**Comment by jrieffel** [comment]
Thanks for all your hard work, voxcraft team!  I *think* I was able to resolve the issue by booting my research computer into single user mode, thereby freeing up the GPU.  Worth keeping this in mind for future resource-poor researchers!

Meanwhile, saving up for a Tesla..

**Comment by skriegman** [comment]
@jrieffel if you document your process, we will share it as "voxcraft for resource-poor researchers" documentation. 

Either way, we are looking forward to see how your lab uses voxcraft.

Keep the issues/pull requests/questions coming!
Sam
