### ISSUE TITLE
Robot Jumps Unexpectedly.

### ISSUE THREAD

**Issue by cfusting** [voxcraft/voxcraft-sim#32]
See https://youtu.be/DyMD2OjOTgU
 
1, 2, 3:

[CMakeOutput.log](https://github.com/voxcraft/voxcraft-sim/files/5683513/CMakeOutput.log)
[base.txt](https://github.com/voxcraft/voxcraft-sim/files/5683516/base.txt)
[robot.txt](https://github.com/voxcraft/voxcraft-sim/files/5683517/robot.txt)

Attached

4.    The specific GPU you are using. Please use nvidia-smi -L to determine this. If you are using google colab, this might change so please get the current gpu.

>RTX 2070

5.    Does your issue also occur on the master branch? Please confirm all source files are being tracked by git and are committed and pushed (git status to confirm). Then please post the git commit that you are using (git log -n 1 to display)

>commit cb983e1c6f7782103f37cd2952369accfe8c2a1a (HEAD -> l-systems, origin/l-systems)

**Comment by skriegman** [comment]
please separate these into separate files

**Comment by cfusting** [comment]
Yeah attaching is the best way to get this done.

**Comment by skriegman** [comment]
I think was resolved, correct? The framerate was too low -- or was it something with collisions/instability?
