### ISSUE TITLE
z-axis fitness is negative 

### ISSUE THREAD

**Issue by cfusting** [voxcraft/voxcraft-sim#33]
Feels like this is above the floor. Z fitness is -0.00000098095390326956, z center of mass is 0.0024990190460967305:

![image](https://user-images.githubusercontent.com/869178/102628783-3cccb000-4118-11eb-9757-898004388710.png)

1, 2, 3 and output:

[robot.txt](https://github.com/voxcraft/voxcraft-sim/files/5716404/robot.txt)
[base.txt](https://github.com/voxcraft/voxcraft-sim/files/5716405/base.txt)
[CMakeOutput.log](https://github.com/voxcraft/voxcraft-sim/files/5716406/CMakeOutput.log)
[output.txt](https://github.com/voxcraft/voxcraft-sim/files/5716412/output.txt)

4. The specific GPU you are using. Please use nvidia-smi -L to determine this. If you are using google colab, this might change so please get the current gpu.

> RTX 2070

5. Does your issue also occur on the master branch? Please confirm all source files are being tracked by git and are committed and pushed (git status to confirm). Then please post the git commit that you are using (git log -n 1 to display)

>commit cb983e1 (HEAD -> l-systems, origin/l-systems)

**Comment by skriegman** [comment]
z center of mass is 0.0025... that's reasonable but not exact.
`Lattice_Dim>0.01</Lattice_Dim>`
The CoM of a voxel on the floor is at most 0.005, and the voxel on top has at most CoM 0.015. 
With three voxels on the floor plus the voxel on top: (3*0.005+0.015)/4=0.03/4=0.0075.

Idk why the fitness_score is 0.
Looks like we will need to debug your setup but can you do a quick test:
What happens you make a series of towers: 1 voxel, 2 voxels (one stacked on top of the other), 3 voxel column, 4, 5, 6...?

**Comment by skriegman** [comment]
Ok I can confirm that I get the same fitness_score with this robot. We can change some of the params here to make debugging faster while preserving the bug. 
`<Elastic_Mod>500</Elastic_Mod>`
And the stop condition can be a fraction of a second.

I made some towers and z (fitness_score) is increasing in each, but incorrect.

**Comment by liusida** [comment]
OK, I think I got this one.

Let's imagine, the z of the floor is -0.005.
So the voxels in the first layer have z of 0.0
the voxels in the second layer have z of 0.01

( 3 * 0 + 1 * 0.01 ) / 4 = 0.0025

**Comment by liusida** [comment]
Sorry for the confusing position of the floor~ :rabbit: 

I can't remember this until I tested the case of one voxel and two voxels.

**Comment by skriegman** [comment]
That makes sense. But what about the fitness_score error?

**Comment by skriegman** [comment]
oh because the fitness score is averaging all of them.
