### ISSUE TITLE
What are the units and range of VXA.VXC.Structure.PhaseOffset?

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#36]
Is it radians (0..2pi) or cycles (0..1) or something else?

https://gpuvoxels.readthedocs.io/en/docs/vxa-vxd/tags.html#vxa-vxc-palette-material 

does not specify.

**Comment by skriegman** [comment]
The unit is actuation cycles; it will accept any real number. Here's how that number is used:

https://github.com/voxcraft/voxcraft-sim/blob/75945922e6ee8ba5a5539a42385e57970385ffd3/src/VX3/VX3_VoxelyzeKernel.cu#L639

**Comment by skriegman** [comment]
We are in the process of updating (and renaming!) the docs. We will add this. Thanks.
