### ISSUE TITLE
Google Colab Runtime Configuration

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#37]
What runtime configuration settings should I be using?  I've been getting the following error using the High-RAM machine with GPU accelleration.

=== set device to 0 for 1 simulations ===

Total GPU memory 16914055168 bytes.
Set GPU heap size to be 8457027584 bytes.

/content/voxcraft-sim/src/VX3/VX3_SimulationManager.cu(413): CUDA Function Error: too many resources requested for launch 
Running simulation locally by default.
./vx3_node_worker -i workspace/locally/20210106152335.vxt -o workspace/locally/20210106152335.vxr

**Comment by skriegman** [comment]
John, as you know we cannot replicate your error without your .vxa/d files!

However, in all likelihood this error is from using too small of a heap size. Perhaps try 0.75 or higher, instead of the default 0.5.

https://gpuvoxels.readthedocs.io/en/docs/vxa-vxd/tags.html#vxa-gpu-heapsize

Please let us know whether or not that resolves the issue.

**Comment by jrieffel** [comment]
(my question was simply about GPU configuration, not asking for debugging help - but now that you offer)

Here is a zip with my vxa, vxd, history, and simulator configuration file.  The config file is where I have updated the HeapSize.  I'd love it if you could take a peek.

[jr-heapsize-data.zip](https://github.com/voxcraft/voxcraft-sim/files/5777065/jr-heapsize-data.zip)

**Comment by skriegman** [comment]
Actually if you are still having this problem, my lab members pointed out that your heapsize might be too large not too small (as I suggested). This is because not everything in the code allocates through the cuda kernel heap.

**Comment by jrieffel** [comment]
That did the trick! Lowered HeapSize to 0.25.  Thank you!
