### ISSUE TITLE
Please provide example .vxd file with PhaseOffset

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#38]
Any chance you could provide a simple example vxd file that contains the correct format for per-voxel PhaseOffset? 

thank you!

**Comment by skriegman** [comment]
You need commas between every float value for phaseoffset, but no commas between every integer 0-9 for the morphology. I realize this is not ideal. It is something we brought over from voxcad that we should probably change.

**Comment by jrieffel** [comment]
An example would help :)

**Comment by skriegman** [comment]
ah yes, having now actually read what you asked, here is an example:
```
<Structure Compression="ASCII_READABLE">
    <X_Voxels>2</X_Voxels>
    <Y_Voxels>2</Y_Voxels>
    <Z_Voxels>2</Z_Voxels>
    <Data>
        <Layer><![CDATA[1111]]></Layer>
        <Layer><![CDATA[0011]]></Layer>
    </Data>
    <PhaseOffset>
        <Layer><![CDATA[-1.0, -0.5, 0.0, 0.5, ]]></Layer>
        <Layer><![CDATA[0.0, 0.0, 0.0, 1.0, ]]></Layer>
    </PhaseOffset>
</Structure>
```
