### ISSUE TITLE
Unexpected behaviors 

### ISSUE THREAD

**Issue by scarlettwei** [voxcraft/voxcraft-sim#39]
While we applied MAP-Elites to discover the capability of certain morphology, we find some unexpected behavior, such as explosion and detachment. Two sample runs are recorded and attached, and hope by comparing them can find what parameter leads to these unexpected behaviors.

https://user-images.githubusercontent.com/60554502/104135847-73d16280-5360-11eb-8053-8ef16de7a4c5.mov

https://user-images.githubusercontent.com/60554502/104135850-759b2600-5360-11eb-889b-b21c61594c3f.mov

1.  Base.VXA and robot.VXD for the morphology 
[Base.txt](https://github.com/voxcraft/voxcraft-sim/files/5793331/Base.txt)
[bot.VXD.txt](https://github.com/voxcraft/voxcraft-sim/files/5793332/bot.VXD.txt)

2. History Files for the recorded behaviors
[sim_run1596.txt](https://github.com/voxcraft/voxcraft-sim/files/5793340/sim_run1596.txt)
[sim_run973.history.txt](https://github.com/voxcraft/voxcraft-sim/files/5793341/sim_run973.history.txt)

3. VXA Files for the recorded behaviors 
[sim_run1596.VXA.txt](https://github.com/voxcraft/voxcraft-sim/files/5793342/sim_run1596.VXA.txt)
[sim_run973_VXA.txt](https://github.com/voxcraft/voxcraft-sim/files/5793343/sim_run973_VXA.txt)

4. Experiments  are done in Google Colab 
`GPU 0: Tesla T4 (UUID: GPU-452ef5d1-2fc3-a1c9-d071-f9a5bf107b18)`

**Comment by skriegman** [comment]
I only read the robot file and watch the videos but the voxels look pretty soft (the elastic modulus divided by the density is a low ratio). What happens when you try a density of 1 and elastic modulus of 10?

But also I've never used different signed CTE in voxels right next to each other. It looks unstable right away. You shouldn't need a dtfrac of 0.5 for something so simple. I guess the system hasn't been tested for a few number of voxels pulling in opposite directions. What happens if the entire thing is one material? Is it stable?

**Comment by scarlettwei** [comment]
When I raised the elastic modulus to 10, the behavior of the voxels in VIZ is less severe. I'll run simulations with MAP-Elites and check the history files.
CTE is one of the parameters we are using, so same material will have the same value. In this case, materials are scattered around the whole robot, so adjacent voxels have different CTE. When the entire thing is just one material, I got explosion when it was all 'flexible' material, but also stable behavior with less flexible materials. 
I'll run few more tests and see what parameters can be used to make the robots more stable.

**Comment by skriegman** [comment]
Were you able to resolve this @scarlettwei?

**Comment by scarlettwei** [comment]
It is not fully solved, we are still getting some unexpected behaviors even with only one material and higher elastic modulus values. But in general the simulations are much stabler than before and we are getting less unexpected behaviors.

**Comment by skriegman** [comment]
Ok @scarlettwei I am going to close this issue. Please open a new one, if necessary, for specific examples
