### ISSUE TITLE
Understanding Phase in Sim vs Viz

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#40]
In the voxcraft-viz palette editor there is a field for TempPhase, which suggests that Phase is a material property.  From reading the documentation and earlier issues, it seems as if Phase is specified per-voxel in the `.vxd` file.

Can you explain what the `TempPhase` field on the Materials Palette is, and how it is different than `VXA.VXC.Structure.PhaseOffset`?

![image](https://user-images.githubusercontent.com/6656810/104509289-74b00180-55b7-11eb-8532-16eb1c3f4fef.png)

**Comment by liusida** [comment]
Temperature Phaseoffset is a material property, but we found that by specifying the phase offset of each voxel, we can have fine control of the movement.

We can see here: https://voxcraft.github.io/zoo, different voxels are controlled by different pipes, so it is possible to give each voxel a phase offset.

The voxcraft-viz is only adopted to play history files, so the content on the GUI might be outdated. 
`base.vxa` + `robot.vxd` is the current way to pass parameters in, and here is the current document: https://voxcraft.readthedocs.io/en/latest/

**Comment by jrieffel** [comment]
So, to clarify:

* it is a Material Property in that it can be edited by the Materials Palette.  
* But it is not a field in the VXA.VXC.Material.Palette the way almost all other material properties are - and can only be changed in the .vxd on a per-voxel basis, rather than changing the phase of all materials of a given type (the way other Material Properties are managed).

**Comment by skriegman** [comment]
We do not use voxcad or the voxelyze backend for anything. And so there are some things that were not carried over directly from voxelyze/voxcad to voxcraft (e.g. material-wise phase shift) when we GPU-ized it.

Repurposing voxcad as voxcraft-viz was simply the easiest way to playback history files. That's it's sole purpose here. I agree it's not clear, and we will rectify this in the new docs.

We are planning on developing a custom visualizer in the the future. In the meantime, you can use whatever you want: https://youtu.be/z0f-I2rZGDU
