### ISSUE TITLE
Installation Questions

### ISSUE THREAD

**Issue by indubeetably** [voxcraft/voxcraft-sim#49]
I need help/ideas with how to install and run VoxCraft on our HPC cluster. I do not have root access on our HPC cluster, so I need to be able to install and run VoxCraft as an unprivileged user. Our cluster uses Singularity as its container tool, like Docker. I can build from local Docker cache with docker-daemon:// and end up with a Singularity container image on the cluster. I can also build from recipe containers on a system where I have elevated privileges and then copy the container to the cluster. Any insights on being able to install and run VoxCraft on our HPC cluster are appreciated. Right now, it seems as if I have to build a container outside of the HPC (and continuously thereafter) before pulling and running it on the HPC...does this sound right? Are there better ways of going about this?

**Comment by skriegman** [comment]
Hey Emmanuel. Do these instructions work for you? Just make sure to replace vacc/deepgreen (UVM’s cluster names) with Yale’s cluster name.

https://github.com/mec-lab/wiki/wiki/Install-voxcraft-on-a-cluster

**Comment by liusida** [comment]
@cfusting is more familiar with Singularity, but I am more familiar with building from source code. 
If Singularity doesn't work for you, @indubeetably , I can help on building from source code.

**Comment by indubeetably** [comment]
Hey, I was able to install voxcraft on a remote machine following the instructions. Thanks for all the help! More requests for assistance to follow.:)
